### ISSUE TITLE
importEPW - directNormalRadiation outputting values in lux instead of W/m2

### ISSUE THREAD

**Issue by patternarch** [mostaphaRoudsari/ladybug#463] opened 2019-08-19 02:52 UTC
Looks like V 0.0.67 NOV_20_2018 version of ImportEPW has Radiation and Illuminance flipped in the outputs. Radiation is in lux and Illuminance is in W/m2. Also directNormalRadiation is reporting diffuse and diffuseHorizontalRadiation is reporting direct components.

**Comment by chriswmackey** [comment] 2019-08-19 14:24
@patternarch ,

This is definitely an issue that is specific to your EPW since a bug this large would have been noticed by myself or any of the other hundreds of active community members on our forum.  Here's a screenshot just for more proof:
![image](https://user-images.githubusercontent.com/5567574/63273133-65664080-c26b-11e9-93bc-2c03057385f2.png)

We can help you figure out what is wrong with your EPW if you upload it to a post on [our forum](https://discourse.ladybug.tools/) but, because this is not a bug in ladybug, I am closing out this issue for now.

**Comment by patternarch** [comment] 2019-08-19 14:31
@chriswmackey This consistently issue is for every TMY3 weather file  We have run every weather file to test this. TMY and TMY2 along with some international locations are correct. I think further exploration is warranted. Thanks for looking into this! Try the USA_AZ_Phoenix-Sky.Harbor.Intl.AP.722780_TMY3.epw for instance.

**Comment by mostaphaRoudsari** [comment] 2019-08-19 14:38
@patternarch, is it happening for weather files from DOE website or OneClimate? Can you send the exact link to the weather file. Thanks.

**Comment by patternarch** [comment] 2019-08-19 14:38
@chriswmackey Also even in the example you show the direct normal radiation is outputting in lux rather than W/m2.

**Comment by patternarch** [comment] 2019-08-19 14:49
@mostaphaRoudsari the climate files come from DOE

**Comment by chriswmackey** [comment] 2019-08-19 17:12
@patternarch ,

If that is the case, then you'll have to explain what you are expecting these results to be since these make sense to me:
![image](https://user-images.githubusercontent.com/5567574/63285101-03193a00-c283-11e9-87ac-9ca3993ad039.png)

**Comment by patternarch** [comment] 2019-08-19 19:21
Okay, looks like I was wrong on the TMY3 files. I thought I was connected to that one. However, I was connected to a TMY format. See screenshot. Radiation is looking correct but Illuminance has problems. Thanks for your patience. I should have put a screen shot in the first time! 
![TMY problem](https://user-images.githubusercontent.com/20159038/63293023-05848f80-c295-11e9-8e98-787c436fe42a.JPG)

**Comment by mostaphaRoudsari** [comment] 2019-08-19 20:22
@patternarch, values >= 999900 are missing values. TMY files are older and it is common that they are missing data. See here: https://bigladdersoftware.com/epx/docs/8-3/auxiliary-programs/energyplus-weather-file-epw-data-dictionary.html#field-diffuse-horizontal-illuminance

There is not much we can do about this. @chriswmackey what are your thoughts?

**Comment by chriswmackey** [comment] 2019-08-19 20:37
Glad that we have come to an agreement that it is an EPW-specific issue and, yes, I agree that there isn't anything that we should change with ladybug legacy to estimate these missing illuminance values.  

However, there are luminous efficacy models within the new ladybug-core Python library that would allow you to estimate the illuminance from the radiation and dewpoint values in the EPW.  I have posted an example file to hydra with a component that uses these libraries to estimate illuminance.  If you post this question about missing illuminance to the forum where I know several people will benefit from seeing the answer, I will give a more detailed explanation and the links to the luminous efficacy model resources.

**Comment by mostaphaRoudsari** [comment] 2019-08-20 18:31
Thank you @chriswmackey! @patternarch I'm going to close this issue as the original question has been resolved. Please post any follow up questions on the forum as suggested by Chris.

**Closed by mostaphaRoudsari** 2019-08-20 18:31 UTC
