### ISSUE TITLE
Wet Bulb Temperature Component

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/ladybug#219] opened 2016-01-18 15:46 UTC
I'm creating the issue to continue the discussion about [the new Wet Bulb component by Antonello](http://www.grasshopper3d.com/xn/detail/2985220:Comment:1439789).

![](http://api.ning.com/files/bZ6KiUmf2vK3cKQ-8W7Ex*0FxlvRU5OAbl2wYvgSv-OHtyyxa8ktXuwurSGOcRRBw9qKONXPwBRvxSaN8Yv8ZGITZZfkLF8Y/WetBulbTemp_02.png)

![](http://api.ning.com/files/bZ6KiUmf2vKIvnOPhIz7FsofJi3a6ycYjoGmzd1VUFLH6hjY1DEEPuCMUIBwjQm6Rjp2xYu4lO2CRTlviHJnZPlCd8xSoQEO/WetBulbTemp_01.png)

**Comment by ayezioro** [comment] 2016-01-18 18:27
Hi,
Mi comment in the discussion was as follows:
Testing the "second mode" in your file i noticed that changing the analysis period changes the results. Sometimes the changes are to big to bare. Try month 1 to 4 and then 1 to 8, etc.
I noticed that this happens when I updated the file in my computer to latest LB_HB, then i get the inconsistencies. Using the LB version in the example file it works fine. 
My suspicion is that something was changed either in the LB_LB or importEPW but i can't tell.
-A.

**Comment by AntonelloDN** [comment] 2016-01-18 19:04
Hi,
Have you also tested the updated version of the component, in the last reply of the discussion?
I'm sorry, I haven't installed the last LB, I'll do it as soon as possible.
In second mode there is other main component:- Ladybug_Average Data - before Wet Bulb. Is it possible that there are some problems with one of these?

Thanks
Antonello

**Comment by ayezioro** [comment] 2016-01-18 19:56
Yes,
I've just tried. Sooo weird.
-A.

**Comment by chriswmackey** [comment] 2016-01-19 04:22
@AntonelloDN and @ayezioro ,

I am sorry for being away for the day.  So much has happened!
I have spent the last few minutes trying to understand the bug that you have been referencing and I am still at a loss.  I can see that Antonello's component is calculating different values for different analysis periods but I can't get any of the other Ladybug components to have this phenomenon.  Am I right in understanding that it is only something that only affects Antonello's component or does it affect the other LB components?  If it is an issue that is not with Antonello's component, could you post a dropbox link to a GH file that has the issue?

On another point, @AntonelloDN , in the interest of making your component a bit more sleek and elegant, it might be best to have the component auto-sense if the format of the data coming in and just output the data in the format that it is input.  So, if it has a header, output the data with a corresponding header and, otherwise, leave it with no header.  Users can always use the other components to add/remove a header if they need it and I feel that 99.9% of the time, people are going to want the data to come out of the component in the same format that goes into it.

Finally, @AntonelloDN , let me know if you want to set up a skype session to go over forking the Ladybug repo and making a pull request.  I am available after 6 PM EST any time this week.  Also, @mostaphaRoudsari 's video series will help you get acquainted with the basics of the ladybug developer components:
https://www.youtube.com/watch?v=n_m5PDqv5pU&list=PLkjfDmSc5Orxq-f_fbmu_HV4tE2ZPIdaC

Looking forward to this!
-Chris

**Comment by mostaphaRoudsari** [comment] 2016-01-19 04:39
Thank you all. @chriswmackey said almost all the comments that I have, and I'm also still lost about the bug. What's exactly the issue?

@AntonelloDN, the only comment that I want to add is to name inputs all camelCase following [Ladybug's Graphic Standards](https://github.com/mostaphaRoudsari/ladybug/blob/master/resources/Ladybug%20Grahpic%20Standards.md). See number 4 for this case.

@AntonelloDN I should probably put a video together about how to fork, add changes and send a pull request using the interface. Most of the videos out there are using command lines which is not easy for someone who wants to get started with Github. Meanwhile let us know if you have any questions.

**Comment by ayezioro** [comment] 2016-01-19 04:52
Hi,
Since i reported this bug maybe i'll try to explain it again. Download Antonello's example in the forum's discussion. Even the last version, or the one before (even better since it contains one group called "Second mode".
The outputs of the new component are shown in the LB_BarChart. So far, so good. You see in this group that we can change the analysis period. In this version, changing the period works fine.
Now ... I updated the file (with the updater component). And here is the problem. Now when you change the period the plotted lines change for the same months. I can't tell where is this happening. Tried different EPW's (local and abroad from my location) and get the same effect.
Didn't tried with other components besides Antonello's.
Is this more clear? Hope so ...
Thanks,
-A.

**Comment by ayezioro** [comment] 2016-01-20 08:16
Hi,
Look also to this comment on another discussion:
http://www.grasshopper3d.com/xn/detail/2985220:Comment:1441940
-A.

**Comment by AntonelloDN** [comment] 2016-01-20 11:13
@chriswmackey,
Thank you for your suggestion, I'll try to make an auto-sense system the better I can. Some advice about it are very appreciated.
I've sent you an email where you can find my skype contact.
@mostaphaRoudsari thank you. I'm going to change almost all name of inputs. 
 I'm little bit confused about Github.. Is it necessary to be member of Github to send you new components or an idea for a new component? Because I don't know if I have good skills for you to stay here, although I have a lot of ideas. If I have to leave Github, please let me know.
@ayezioro, I installed the last version of LB HB. Could you send me your example file so I can see the issue that you talk about? If you are agree, you should add recorder elements or something like these to your gh file. In this way, I can see values of lists precisely. Thank you.

**Comment by ayezioro** [comment] 2016-01-20 12:12
@AntonelloDN,
The example is the one you uploaded in the discussion. And the case is the "second mode".
See the image here to see what's happenning. Same weather file, different periods (1-4 and 1-8).
-A.
![capture](https://cloud.githubusercontent.com/assets/7526023/12448601/d314a330-bf7f-11e5-8cf4-05c28d214ea2.JPG)

**Comment by AntonelloDN** [comment] 2016-01-20 15:15
@ayezioro I have found some bugs in the new version of Ladybug_Monthly Bar Chart and I have just fixed them. As you can see, in your graph the line of dry bulb temperature is often above the ones of wet bulb temperature and dew point temperature. It is really strange and impossible.

the wrong lines of the script are:

160
527
544
556
564
567
578

Put these instead of the actual lines:

if list[3] == 'F' or list[3] == '°F': farenheitCheck = True

if unitsList[0] == 'C' or unitsList[0] == '°C' or unitsList[0] == 'F' or unitsList[0] == '°F':

if unit.strip('°') != unit1.strip('°') and done == False:

if unit2 == 'C' or unit2 == '°C' or unit2 == 'F' or unit2 == '°F':

elif unit.strip('°') == unit1.strip('°'):

if unit1 == 'C' or unit1 == '°C' or unit1 == 'F' or unit1 == '°F':

if unitsList[uCount+1] == 'C' or unitsList[uCount+1] == '°C' or unitsList[uCount+1] == 'F' or unitsList[uCount+1] == '°F':

![corrige](https://cloud.githubusercontent.com/assets/16763953/12451998/9a237990-bf8c-11e5-8235-857c3edeef18.png)

I think the problem is that the script puts directly the other temperature data on the right side of the graph, for this reason in your image it can see "Wet bulb temperature" and other values.
Below the test adding relative humidity after bug-fixing.
![corrige_2](https://cloud.githubusercontent.com/assets/16763953/12452428/bab228bc-bf8e-11e5-8a7d-24cdde15ef9c.png)
![corrige_3](https://cloud.githubusercontent.com/assets/16763953/12452656/dcfd6c00-bf8f-11e5-9f21-7efddd5311fa.png)
![corrige_4](https://cloud.githubusercontent.com/assets/16763953/12452660/e16ec22a-bf8f-11e5-9b99-27a5e6dad100.png)

**Comment by chriswmackey** [comment] 2016-01-21 02:20
@AntonelloDN ,
You are on fire, man!  Fixing bugs in the monthly bar chart! Those ones look like they are the result of a recent feature that I added, which I clearly did not test well enough.  When we skype, I will have you commit your bug fixes for the chart along with the wet bulb component such that that you get credit for the contributions here on the github.
I saw that you sent me an email and I will send you possible skype times there.
Looking forward to having both of these contributions integrated!
-Chris

**Comment by ayezioro** [comment] 2016-01-21 05:29
Very nice!!
Thanks,
-A.

**Comment by AntonelloDN** [comment] 2016-01-22 18:01
Hi @chriswmackey and @ayezioro 

I have understood the issue between my component and the monthly bar chart , I wrote "°C" instead "C" therefore the monthly bar chart works fine. So it's more easy change my component. I'll do that.

I have found a small bug in the Honeybee_Visualize Microclimate Map.
http://www.grasshopper3d.com/xn/detail/2985220:Comment:1441940 
the wrong line should be: 404
if len(analysisPeriod_) == 0 or annualData == False

Try this:
if len(analysisPeriod_) == 0 and annualData == False
Please let me know your opinion.
![canvas at 17 55 43](https://cloud.githubusercontent.com/assets/16763953/12517570/a085c574-c133-11e5-9244-124191427e32.png)
![canvas at 17 56 10](https://cloud.githubusercontent.com/assets/16763953/12517578/ae137de4-c133-11e5-8fd7-e47d336a35d0.png)

**Comment by mostaphaRoudsari** [comment] 2016-01-24 03:39
@AntonelloDN I checked the names of the component today and a number of them are still Capitalized.

![image](https://cloud.githubusercontent.com/assets/2915573/12534332/01f3c2a4-c222-11e5-8a81-c3b1d50fe042.png)

Would be great if you can get them fixed before we move the component from WIP.

**Comment by chriswmackey** [comment] 2017-12-22 00:19
Now that all of the issues in this post have been addressed and this component has long-been a good contribution to the project, I am closing out this issue. Thank you @AntonelloDN for this great component!

**Closed by chriswmackey** 2017-12-22 00:19 UTC
Labels: New Component
